#!/usr/bin/env bash

# for use in my find invocations - I only want to work with certain audio types
FORMATS='.*\(mp3\|mp4\|flac\)'

FIFO=/var/tmp/.fifo
MY_STDOUT=/var/tmp/.ohmm_out
QUEUE=/var/tmp/.plyst
SLEEP=.1s
IS_SHUFFLE=false

VOLUME=100
V_INC=10
LOOP=-1

LIBRARY="$EXE_PATH/library"

